[phases.setup]
nixPkgs = ["nodejs", "gcc", "gnumake"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "cd bbpPairings && make clean && make && cd ..",
  "npm run build"
]

[start]
cmd = "npm start"
